//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnd_App.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbilityScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbilityScore()
        {
            this.NPC_AbilityScore = new HashSet<NPC_AbilityScore>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string shortName { get; set; }
        public int value { get; set; }
        public int modValue { get; set; }
        public bool savingThrow { get; set; }
        public int bonus { get; set; }
        public int inputValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPC_AbilityScore> NPC_AbilityScore { get; set; }
    }
}
