//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnd_App.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.NPC_Action = new HashSet<NPC_Action>();
            this.PC_Action = new HashSet<PC_Action>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string limited { get; set; }
        public string description { get; set; }
        public int bonusDamage { get; set; }
        public int range { get; set; }
        public string target { get; set; }
        public int damage { get; set; }
        public int typeAction { get; set; }
        public int bonusAttack { get; set; }
        public int totalBonusAttack { get; set; }
        public string abilityAction { get; set; }
        public int min { get; set; }
        public int max { get; set; }
        public int hitDie { get; set; }
        public int die { get; set; }
        public int abilityDamage { get; set; }
        public int typeDamage { get; set; }
        public int Actiontype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NPC_Action> NPC_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_Action> PC_Action { get; set; }
    }
}
